### PR TITLE
[!!!][TASK] Rename namespace to Flowpack\JobQueue and switch to PSR-4

### PR DESCRIPTION
**Pull request by robertlemke**
This change moves the whole package to the Flowpack namespace (also note
the corrected spelling of JobQueue), switches the directory structure
to PSR-4 and adds an example configuration to Settings.yaml

### CODE REVIEW

**Comment by robertlemke** [comment]
:+1:

**Comment by kdambekalns** [comment]
Looks good.

**Comment by dfeyer** [comment]
:+1:

**Comment by bwaidelich** [comment]
I'm late to the party but thanks for this ;) I'm taking care of polishing the job queue packages a bit and wondered: How could this change work without adjusting any of the two implementing packages (https://github.com/Flowpack/jobqueue-redis and https://github.com/Flowpack/jobqueue-beanstalkd)? Or do I miss something?

**Comment by dlubitz** [comment]
It doesn't ;)
See: https://github.com/Flowpack/jobqueue-redis/pull/1

**Comment by bwaidelich** [comment]
> It doesn't ;) See: Flowpack/jobqueue-redis#1

Right, I'll take care of this one now.. Thanks

**Pull request merged**
